/**
 * Generate template code + files from wizard state
 * 
 * V3-1.3: Fixed to actually generate usable files by running bigpicture-v1
 * generator with niche defaults. Previously only generated source code string
 * but no actual files — templates saved to DB were empty shells.
 * 
 * Strategy: Run bigpicture-v1 engine with niche-specific config overrides.
 * The output includes both:
 * - sourceCode: JS module string (for reference/download)
 * - files: Actual Astro project files (for rendering + deploy)
 */

import { generate as moduleGenerate } from '#lp-template-generator/core/generator.js';

export const TEMPLATE_AI_EDITABLE_FILES = [
  "src/layouts/Layout.astro",
  "src/styles/global.css",
  "tailwind.config.mjs",
];

// Niche presets — default copy & config overrides per niche
const NICHE_PRESETS = {
  installment: {
    loanType: 'installment',
    h1: 'Get Cash Fast',
    h1span: '$100–$5,000',
    badge: '✓ No Credit Check Required',
    cta: 'Check My Rate →',
    sub: 'Fast approval. Funds as soon as tomorrow.',
    metaTitle: '{brand} | Installment Loans $100–$5,000 — Apply Online',
    metaDesc: 'Apply in 2 minutes for installment loans up to $5,000. No hidden fees, instant decision.',
    amounts: [500, 1000, 2000, 3000, 5000],
    amountMin: 100, amountMax: 5000,
    aprMin: 5.99, aprMax: 35.99,
    faqItems: [
      { q: 'How much can I borrow?', a: 'You can request between $100 and $5,000 depending on your state and qualifications.' },
      { q: 'Will this affect my credit score?', a: 'No! Checking your rate uses a soft pull that won\'t affect your credit score.' },
      { q: 'How fast can I get funds?', a: 'If approved, funds can be deposited as soon as the next business day.' },
      { q: 'What are the requirements?', a: 'You need to be 18+, a US resident, have a bank account and regular income.' },
    ],
  },
  'pet-care': {
    loanType: 'pet-care',
    h1: 'Pet Care Financing',
    h1span: 'Made Simple',
    badge: '🐾 0% APR Options Available',
    cta: 'Check My Options →',
    sub: 'Affordable payment plans for your pet\'s health.',
    metaTitle: '{brand} | Pet Care Financing — Affordable Payment Plans',
    metaDesc: 'Finance your pet\'s veterinary care with flexible payment plans. 0% APR options available.',
    amounts: [500, 1000, 2000, 3000, 5000],
    amountMin: 200, amountMax: 10000,
    aprMin: 0, aprMax: 29.99,
    faqItems: [
      { q: 'What veterinary services are covered?', a: 'Most veterinary procedures including surgery, dental, emergency care, and wellness visits.' },
      { q: 'Is there a 0% APR option?', a: 'Yes! Qualifying applicants may receive 0% APR promotional financing.' },
      { q: 'How do I use the financing?', a: 'Once approved, present your approval at any participating veterinary clinic.' },
      { q: 'Will this affect my credit?', a: 'Checking your options uses a soft inquiry that won\'t impact your credit score.' },
    ],
  },
  general: {
    loanType: 'installment',
    h1: 'Smart Financial Solutions',
    h1span: 'For You',
    badge: '✓ Fast & Secure',
    cta: 'Get Started →',
    sub: 'Simple application. Quick decision. Trusted by thousands.',
    metaTitle: '{brand} | Apply Online Today',
    metaDesc: 'Apply online in minutes. Fast approval, competitive rates, no hidden fees.',
    amounts: [1000, 2000, 3000, 4000, 5000],
    amountMin: 100, amountMax: 5000,
    aprMin: 5.99, aprMax: 35.99,
    faqItems: [
      { q: 'How does it work?', a: 'Simply fill out our short online form. Get a decision in minutes.' },
      { q: 'Is it safe?', a: 'Yes. We use 256-bit encryption to protect your personal information.' },
      { q: 'How fast is approval?', a: 'Most applications receive a decision within minutes.' },
      { q: 'Are there hidden fees?', a: 'No hidden fees. All terms are clearly disclosed before you accept.' },
    ],
  },
};

/**
 * Generate source code string (JS module wrapper) — for reference/download only
 */
export function generateTemplateCode(state) {
  const {
    templateName = "My Template",
    templateDescription = "Custom template",
    category = "general",
    heroStyle = "cards",
    hasFAQ = true,
    hasTrustBadges = true,
    hasDarkMode = true,
    colorId = "ocean",
    fontId = "inter",
  } = state;

  const niche = NICHE_PRESETS[category] || NICHE_PRESETS.general;

  const code = `/**
 * ${templateName}
 * ${templateDescription}
 * Auto-generated by FusionOps Template Wizard
 * Base: bigpicture-v1 (worker-safe, variant support)
 */

import { generate as baseGenerate } from '../bigpicture-v1/index.js';

const DEFAULTS = ${JSON.stringify({
    loanType: niche.loanType,
    h1: niche.h1,
    h1span: niche.h1span,
    badge: niche.badge,
    cta: niche.cta,
    sub: niche.sub,
    metaTitle: niche.metaTitle,
    metaDesc: niche.metaDesc,
    amounts: niche.amounts,
    amountMin: niche.amountMin,
    amountMax: niche.amountMax,
    aprMin: niche.aprMin,
    aprMax: niche.aprMax,
    colorId,
    fontId,
    heroVariant: heroStyle,
    themeVariant: hasDarkMode ? 'dark' : 'dark',
    stickyBar: true,
    trustVariant: hasTrustBadges ? 'icons' : 'icons',
    faqVariant: hasFAQ ? 'accordion' : 'accordion',
  }, null, 2)};

export function generate(site) {
  const merged = { ...DEFAULTS, ...site };
  if (!site.metaTitle) merged.metaTitle = DEFAULTS.metaTitle.replace('{brand}', merged.brand || '');
  if (!site.metaDesc) merged.metaDesc = DEFAULTS.metaDesc;
  return baseGenerate(merged);
}
`;

  return code;
}

/**
 * Generate actual Astro project files by running bigpicture-v1 generator
 * with niche defaults. These files are what gets saved to DB and used for
 * preview + deploy.
 */
export function generateTemplateFiles(state) {
  const category = state.category || 'general';
  const niche = NICHE_PRESETS[category] || NICHE_PRESETS.general;

  // Build config that bigpicture-v1 expects
  const config = {
    brand: state.templateName || 'Custom Brand',
    domain: 'example.com',
    email: 'support@example.com',
    ...niche,
    colorId: state.colorId || 'ocean',
    fontId: state.fontId || 'inter',
    heroVariant: state.heroStyle || 'cards',
    themeVariant: state.hasDarkMode !== false ? 'dark' : 'dark',
    stickyBar: true,
    trustVariant: state.hasTrustBadges !== false ? 'icons' : 'icons',
    faqVariant: state.hasFAQ !== false ? 'accordion' : 'accordion',
    // Template variables that bigpicture-v1 needs
    templateId: 'template-01',
  };

  try {
    const result = moduleGenerate('template-01', config);
    if (result?.ok && result.files) {
      return { ok: true, files: result.files, errors: [] };
    }
    return { ok: false, files: null, errors: result?.errors || ['Generator returned no files'] };
  } catch (e) {
    console.error('[TemplateGen] Generate files failed:', e);
    return { ok: false, files: null, errors: [e.message] };
  }
}

/**
 * Generate full template config for saving to DB
 * Includes both source code (reference) and actual files (for rendering)
 */
export function generateTemplateConfig(state) {
  const category = state.category || 'general';
  const niche = NICHE_PRESETS[category] || NICHE_PRESETS.general;

  // Generate actual files
  const fileResult = generateTemplateFiles(state);

  return {
    templateId: (state.templateName || 'custom').toLowerCase().replace(/[^a-z0-9]/g, '-'),
    name: state.templateName || 'Custom Template',
    description: state.templateDescription || 'Auto-generated template',
    category: category,
    badge: state.badge || 'New',
    niche: category,
    defaults: {
      ...niche,
      colorId: state.colorId || 'ocean',
      fontId: state.fontId || 'inter',
      heroVariant: state.heroStyle || 'cards',
      themeVariant: state.hasDarkMode !== false ? 'dark' : 'dark',
      stickyBar: true,
      __aiTemplateOnly: true,
      __aiEditableFiles: TEMPLATE_AI_EDITABLE_FILES,
    },
    sourceCode: generateTemplateCode(state),
    files: fileResult.ok ? fileResult.files : {},
    fileErrors: fileResult.errors,
  };
}

export { NICHE_PRESETS };
