#!/usr/bin/env node

/**
 * Build Variant Script
 *
 * Usage: node build-variant.mjs --config theme.json
 *
 * This script builds a specific variant of the landing page
 * with custom theme, content, and tracking configuration.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Parse command line arguments
const args = process.argv.slice(2);
const configPath = args.find(a => a.startsWith('--config='))?.split('=')[1] ||
                     args.find(a => a === '--config') ?
                     args[args.indexOf('--config') + 1] :
                     'theme.json';

// Load theme configuration
let theme;
try {
  const themeContent = fs.readFileSync(configPath, 'utf-8');
  theme = JSON.parse(themeContent);
  console.log(`\x1b[36m✓\x1b[0m Loaded theme: ${theme.brand} (${theme.variant})`);
} catch (error) {
  console.error(`\x1b[31m✗\x1b[0m Failed to load theme config: ${error.message}`);
  process.exit(1);
}

// Backup current files
const backupDir = path.join(__dirname, '.backup');
if (!fs.existsSync(backupDir)) {
  fs.mkdirSync(backupDir, { recursive: true });
}

const filesToBackup = [
  'src/config/brands.ts',
  'src/styles/global.css',
  'src/pages/index.astro',
  'src/components/Header.astro',
  'src/components/Footer.astro'
];

console.log('\x1b[36m→\x1b[0m Backing up current files...');
filesToBackup.forEach(file => {
  const src = path.join(__dirname, file);
  if (fs.existsSync(src)) {
    const dest = path.join(backupDir, file.replace(/\//g, '_'));
    fs.copyFileSync(src, dest);
  }
});

// Update brands.ts
console.log('\x1b[36m→\x1b[0m Updating brand configuration...');
const brandsTemplate = `/**
 * Brand Configuration for ${theme.brand}
 *
 * Variant: ${theme.variant}
 * Auto-generated by build-variant.mjs
 */

export interface BrandConfig {
  brand: string;
  domain: string;
  gads_conversion_id: string;
  gads_labels: {
    form_start: string;
    form_submit: string;
  };
  aid: string;
  voluum?: {
    campaign_url: string;
  };
}

export const DEFAULT_BRAND: BrandConfig = {
  brand: '${theme.variant}',
  domain: '${theme.domain}',
  gads_conversion_id: '${theme.tracking.gads_conversion_id}',
  gads_labels: {
    form_start: '${theme.tracking.gads_labels.form_start}',
    form_submit: '${theme.tracking.gads_labels.form_submit}',
  },
  aid: '${theme.tracking.aid}',
};

export function getBrandConfig(brand: string = DEFAULT_BRAND.brand): BrandConfig {
  return DEFAULT_BRAND;
}

export function getInjectedConfig() {
  const config = getBrandConfig();
  return {
    conversionId: config.gads_conversion_id,
    formStartLabel: config.gads_labels.form_start,
    formSubmitLabel: config.gads_labels.form_submit,
    aid: config.aid,
    pixelUrl: '${theme.tracking.pixel_url}',
  };
}
`;

fs.writeFileSync(
  path.join(__dirname, 'src/config/brands.ts'),
  brandsTemplate
);

// Update global.css with new colors
console.log('\x1b[36m→\x1b[0m Updating CSS variables...');
let globalCss = fs.readFileSync(path.join(__dirname, 'src/styles/global.css'), 'utf-8');

// Replace color variables
globalCss = globalCss.replace(/--primary:\s*\d+\s+\d+%\s+\d+%/, `--primary: ${theme.theme.colors.primary}`);
globalCss = globalCss.replace(/--accent:\s*\d+\s+\d+%\s+\d+%/, `--accent: ${theme.theme.colors.accent}`);
globalCss = globalCss.replace(/--secondary:\s*\d+\s+\d+%\s+\d+%/, `--secondary: ${theme.theme.colors.secondary}`);
globalCss = globalCss.replace(/--radius:\s*[\d.]+(rem|px)/, `--radius: ${theme.theme.radius}`);

fs.writeFileSync(
  path.join(__dirname, 'src/styles/global.css'),
  globalCss
);

// Update Layout.astro with new font
console.log('\x1b[36m→\x1b[0m Updating font...');
let layoutContent = fs.readFileSync(path.join(__dirname, 'src/layouts/Layout.astro'), 'utf-8');

// Replace Google Fonts URL with DM Sans
const fontRegex = /family=Lexend[^&"]*/g;
layoutContent = layoutContent.replace(fontRegex, `family=${theme.theme.font.replace(' ', '+').replace(',', '|')}`);
layoutContent = layoutContent.replace(/font-family: 'Lexend'/g, `font-family: '${theme.theme.font}'`);

fs.writeFileSync(
  path.join(__dirname, 'src/layouts/Layout.astro'),
  layoutContent
);

// Update index.astro with new content
console.log('\x1b[36m→\x1b[0m Updating page content...');
let indexContent = fs.readFileSync(path.join(__dirname, 'src/pages/index.astro'), 'utf-8');

// Replace hero title
indexContent = indexContent.replace(
  /<h1[^>]*>.*?<\/h1>/s,
  `<h1\n            class="text-4xl md:text-5xl lg:text-[3.5rem] font-bold leading-[1.1] mb-6"\n          >\n            ${theme.content.heroTitle}\n          </h1>`
);

// Replace hero subtitle
indexContent = indexContent.replace(
  /<p class="text-lg md:text-xl text-white\/70 max-w-lg mx-auto mb-8">.*?<\/p>/s,
  `<p class="text-lg md:text-xl text-white/70 max-w-lg mx-auto mb-8">\n            ${theme.content.heroSubtitle}\n          </p>`
);

// Replace stat
indexContent = indexContent.replace(
  /\d+,\d+\+[^<]*</,
  `${theme.content.heroStats.primary} ${theme.content.heroStats.text}<`
);

// Replace CTA
indexContent = indexContent.replace(
  /Get Started Now/g,
  theme.content.cta
);

// Replace brand name in references
indexContent = indexContent.replace(/ScratchPayWellPet/g, theme.brand);
indexContent = indexContent.replace(/ScratchPayWellPet/g, theme.brand);

fs.writeFileSync(
  path.join(__dirname, 'src/pages/index.astro'),
  indexContent
);

// Update Header
console.log('\x1b[36m→\x1b[0m Updating header...');
let headerContent = fs.readFileSync(path.join(__dirname, 'src/components/Header.astro'), 'utf-8');

// Replace CTA text
headerContent = headerContent.replace(/Get Started/g, theme.content.cta);
headerContent = headerContent.replace(/Scratch<span[^>]*>PayWellPet<\/span>/g, theme.brand.replace(/\s+/g, '<span class="bg-clip-text text-transparent" style="background-image:linear-gradient(135deg,hsl(25 95% 58%),hsl(25 95% 48%))">$&</span>'));

fs.writeFileSync(
  path.join(__dirname, 'src/components/Header.astro'),
  headerContent
);

// Update Footer
console.log('\x1b[36m→\x1b[0m Updating footer...');
let footerContent = fs.readFileSync(path.join(__dirname, 'src/components/Footer.astro'), 'utf-8');

footerContent = footerContent.replace(/ScratchPayWellPet/g, theme.brand);
footerContent = footerContent.replace(/ScratchPayWellPet/g, theme.brand);
footerContent = footerContent.replace(/support@scratchpaywellpet\.com/g, `support@${theme.domain.replace('www.', '')}`);

fs.writeFileSync(
  path.join(__dirname, 'src/components/Footer.astro'),
  footerContent
);

// Build the project
console.log('\x1b[36m→\x1b[0m Building project...');
try {
  execSync('npm run build', { cwd: __dirname, stdio: 'inherit' });
  console.log('\x1b[32m✓\x1b[0m Build complete!');
} catch (error) {
  console.error('\x1b[31m✗\x1b[0m Build failed:', error.message);
  process.exit(1);
}

// Summary
console.log('\n\x1b[32m═══════════════════════════════════════\x1b[0m');
console.log(`\x1b[1m${theme.brand}\x1b[0m variant built successfully!`);
console.log(`\x1b[90mVariant:\x1b[0m ${theme.variant}`);
console.log(`\x1b[90mDomain:\x1b[0m ${theme.domain}`);
console.log(`\x1b[90mOutput:\x1b[0m dist/`);
console.log('\x1b[32m═══════════════════════════════════════\x1b[0m\n');

console.log('Next steps:');
console.log(`  1. Upload files from dist/ to ${theme.domain}`);
console.log('  2. Update Google Ads IDs in src/config/brands.ts');
console.log('  3. Run: node build-variant.mjs --restore to restore original files\n');
