/**
 * Brand Configuration for ElasticCredits
 *
 * Variant: tpxtna
 * Auto-generated by build-variant.mjs
 */

export interface BrandConfig {
  brand: string;
  domain: string;
  gads_conversion_id: string;
  gads_labels: {
    form_start: string;
    form_submit: string;
  };
  aid: string;
  voluum?: {
    campaign_url: string;
  };
}

export const DEFAULT_BRAND: BrandConfig = {
  brand: 'tpxtna',
  domain: '',
  gads_conversion_id: '',
  gads_labels: {
    form_start: '',
    form_submit: '',
  },
  aid: '',
};

export function getBrandConfig(brand: string = DEFAULT_BRAND.brand): BrandConfig {
  return DEFAULT_BRAND;
}

export function getInjectedConfig() {
  const config = getBrandConfig();
  return {
    conversionId: config.gads_conversion_id,
    formStartLabel: config.gads_labels.form_start,
    formSubmitLabel: config.gads_labels.form_submit,
    aid: config.aid,
    pixelUrl: '',
  };
}
